[server]
folderWatchBlacklist = ["data", "templates", "solver", "export"]

[theme]
primaryColor="#818CF8"
backgroundColor="#111113"
secondaryBackgroundColor="#1A1A1E"
textColor="#E8E8ED"
font="sans serif"
